### ISSUE TITLE
Consider PRs to prismatic/schema?

### ISSUE THREAD

**Issue by ccann** [KitApps/schema-refined#10]
This looks really useful! Nice work and thanks!

I'm wondering if the long term goal is to maintain this as a separate library or to try to port some of the refined functionality into Schema itself? There are a few other schema "utility" libraries out there too like `metosin/schema-tools` and I can envision them unified back into Schema or into one ultimate schema++ library.

Either way, thanks! something to consider

**Comment by ccann** [comment]
Sounds like a great way to move forward. I'll definitely be giving this a shot soon.

**Comment by kachayev** [comment]
Sure thing @ccann! Tell us how it goes and if this works for you, any feedback would be super valuable for us!
