### ISSUE TITLE
Reimplement Struct and DispatchStruct using higher level Schema protocols

### ISSUE THREAD

**Issue by kachayev** [KitApps/schema-refined#5]
The main reason for the change is to simplify implementation and do not rely on the internal mechanics of Schema library itself.

**Comment by gsnewmark** [comment]
@kachayev what to you mean by `higher level Schema protocols`? Implementing only `schema.core/Schema` and not relying on `schema.spec.core/CoreSpec`?

**Comment by kachayev** [comment]
@gsnewmark More about using `variant-spec` etc, like it's done [here](https://github.com/KitApps/schema-refined/blob/51e5dc9ce7d81a0297f12ac7fbd06bae98694379/src/schema_refined/core.clj#L111-L118)

**Comment by gsnewmark** [comment]
Closing the issue since it doesn't really make sense to switch the implementation. Detailed explanation is here https://github.com/KitApps/schema-refined/pull/22
